### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by gab0gomes** [mauriciosoares01/react-native-custom-switches#1]
Fala Maurício, blz?

Tenho uma sugestão de melhoria de semântica, aí tu avalia se é legal.

Que tal trocar left/right por algo como enabled/disabled já que as labels representam diretamente o status do componente?

Valeu! 😄

**Comment by mauriciosoares01** [comment]
Boa cara! Farei o ajuste. Realmente dei uma viajada.
